# Generated by Django 3.1.5 on 2021-01-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210110_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
