# Generated by Django 3.1.5 on 2021-01-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210112_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
