# Generated by Django 3.1.5 on 2021-01-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210112_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
